"""update fixes

Revision ID: 369c676367f6
Revises: 0415447fcbc7
Create Date: 2026-08-03 16:29:37.895002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369c676367f6'
down_revision: Union[str, Sequence[str], None] = '0415447fcbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_faq', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'unanswered_questions', ['conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unanswered_questions', type_='unique')
    op.drop_column('hotel_faq', 'updated_at')
    # ### end Alembic commands ###
