"""id type change

Revision ID: 748405e26d74
Revises: 76f149bf34bf
Create Date: 2026-06-24 13:17:19.239548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748405e26d74'
down_revision: Union[str, Sequence[str], None] = '76f149bf34bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1 — Drop all foreign key constraints first
    op.drop_constraint('unanswered_questions_conversation_id_fkey', 'unanswered_questions', type_='foreignkey')
    op.drop_constraint('conversations_hotel_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('hotel_admin_id_fkey', 'hotel', type_='foreignkey')
    op.drop_constraint('hotel_faq_hotel_id_fkey', 'hotel_faq', type_='foreignkey')

    # Step 2 — Alter all id columns
    op.alter_column('users', 'id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('hotel', 'id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('hotel', 'admin_id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('hotel_faq', 'id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('hotel_faq', 'hotel_id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('conversations', 'id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('conversations', 'hotel_id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('unanswered_questions', 'id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.alter_column('unanswered_questions', 'conversation_id', existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)

    # Step 3 — Re-add all foreign key constraints
    op.create_foreign_key('hotel_admin_id_fkey', 'hotel', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hotel_faq_hotel_id_fkey', 'hotel_faq', 'hotel', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversations_hotel_id_fkey', 'conversations', 'hotel', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('unanswered_questions_conversation_id_fkey', 'unanswered_questions', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('unanswered_questions', 'conversation_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('unanswered_questions', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('hotel_faq', 'hotel_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('hotel_faq', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('hotel', 'admin_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('hotel', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('conversations', 'hotel_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
