"""update time for faqs

Revision ID: 9992a49c988c
Revises: 748405e26d74
Create Date: 2026-07-15 12:50:53.178974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9992a49c988c'
down_revision: Union[str, Sequence[str], None] = '748405e26d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unanswered_questions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unanswered_questions', 'updated_at')
    # ### end Alembic commands ###
